import "dotenv/config"; import mongoose from "mongoose"; import bcrypt from "bcryptjs"; import {env} from "../config/env";
import {User,Customer,Mechanic,Service,Booking,Notification,AuditLog} from "../models";
const rng=(seed:number)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}; const r=rng(20260901);
const pick=<T>(a:readonly T[])=>a[Math.floor(r()*a.length)]!; const n=(a:number,b:number)=>Math.floor(r()*(b-a+1))+a;
const first=["Aarav","Vivaan","Aditya","Arjun","Rahul","Rohan","Kunal","Yash","Ananya","Isha","Priya","Neha","Kavya","Meera","Aditi","Sneha","Pooja","Nisha","Simran","Riya"],last=["Sharma","Gupta","Verma","Singh","Kumar","Mehta","Malhotra","Bansal","Kapoor","Saxena","Chauhan","Agarwal","Mishra","Jain","Arora"];
const areas=["Dwarka","Rohini","Saket","Lajpat Nagar","Vasant Kunj","Pitampura","Janakpuri","Mayur Vihar","Karol Bagh","Rajouri Garden","Greater Kailash","Shahdara","Noida Sector 18","Vasundhara"];
const cars=[["Maruti","Swift"],["Maruti","Baleno"],["Hyundai","i20"],["Hyundai","Creta"],["Tata","Nexon"],["Tata","Punch"],["Honda","City"],["Honda","Amaze"],["Toyota","Innova"],["Kia","Seltos"],["Mahindra","XUV700"],["MG","Hector"],["Volkswagen","Virtus"]];
const services=[["Oil Change","MAINTENANCE","Engine oil and filter replacement",899,45],["Battery Replacement","BATTERY","Battery replacement",5499,60],["Brake Inspection","REPAIR","Brake system inspection",699,45],["Brake Pad Replacement","REPAIR","Brake pad replacement",2499,90],["Engine Diagnostics","DIAGNOSTICS","OBD engine diagnostics",1299,60],["AC Service","MAINTENANCE","AC inspection and service",1799,90],["Wheel Alignment","TYRES","Computerized wheel alignment",999,45],["Tyre Replacement","TYRES","Tyre fitting and balancing",3999,60],["General Service","MAINTENANCE","Multi-point service",2499,150],["Car Wash","CLEANING","Interior and exterior cleaning",599,60]] as const;
const phone=()=>`+91 ${n(700,999)}${n(1000000,9999999)}`; const loc=()=>({latitude:28.48+r()*0.30,longitude:77.10+r()*0.32});
async function seed(){
 await mongoose.connect(env.mongoUri);
 await Promise.all([Booking.deleteMany({}),Mechanic.deleteMany({}),Customer.deleteMany({}),Service.deleteMany({}),User.deleteMany({}),Notification.deleteMany({}),AuditLog.deleteMany({})]);
 const pa=await bcrypt.hash("Admin@123",12),po=await bcrypt.hash("Ops@123",12);
 await User.insertMany([{name:"Instant Mechanic Admin",email:"admin@instantmechanic.com",passwordHash:pa,role:"ADMIN"},{name:"Operations Admin",email:"admin.ops@instantmechanic.com",passwordHash:pa,role:"ADMIN"},...["Priya","Rohan","Neha"].map((x,i)=>({name:`${x} Operations`,email:`ops${i+1}@instantmechanic.com`,passwordHash:po,role:"OPERATIONS"}))]);
 const sv=await Service.insertMany(services.map(([name,category,description,basePrice,estimatedDuration])=>({name,category,description,basePrice,estimatedDuration,isActive:true})));
 const cs=await Customer.insertMany(Array.from({length:120},(_,i)=>{const name=`${pick(first)} ${pick(last)}`;return{customerId:`CUS-${10001+i}`,name,email:`customer${i+1}@example.com`,phone:phone(),address:`${n(1,999)}, ${pick(areas)}, Delhi NCR`,city:"Delhi"}}));
 const ms=await Mechanic.insertMany(Array.from({length:30},(_,i)=>({mechanicId:`MEC-${2001+i}`,name:`${pick(first)} ${pick(last)}`,email:`mechanic${i+1}@instantmechanic.com`,phone:phone(),avatar:`https://i.pravatar.cc/150?img=${i+1}`,status:pick(["AVAILABLE","BUSY","ON_THE_WAY","OFFLINE"] as const),specializations:[pick(["Engine","Brakes","Electrical","AC","Tyres","Diagnostics","General Service"]),pick(["Engine","Brakes","Electrical","AC","Tyres","Diagnostics","General Service"])],location:loc(),jobsCompleted:n(40,480),rating:Number((4+r()).toFixed(2))})));
 const now=Date.now(), stats=new Map<string,{count:number,spent:number}>(), mstats=new Map<string,number>(), bookings:any[]=[];
 for(let i=0;i<1250;i++){const c=pick(cs),s=pick(sv),days=n(-30,90),scheduled=new Date(now-days*86400000-n(0,23)*3600000);let status=pick(["PENDING","ASSIGNED","MECHANIC_ON_THE_WAY","IN_PROGRESS","COMPLETED","CANCELLED"] as const);if(scheduled>new Date())status=pick(["PENDING","ASSIGNED","MECHANIC_ON_THE_WAY"] as const);if(scheduled<new Date(now-2*86400000)&&["PENDING","ASSIGNED","MECHANIC_ON_THE_WAY","IN_PROGRESS"].includes(status))status=pick(["COMPLETED","CANCELLED"] as const);const m=["PENDING","CANCELLED"].includes(status)?null:pick(ms),amount=Math.round(s.basePrice*(.9+r()*.2));const b:any={bookingId:`BK-${100000+i}`,customer:c._id,vehicle:{make:cars[i%cars.length]![0],model:cars[i%cars.length]![1],year:n(2017,2025),registrationNumber:`DL ${n(1,9)}C ${n(1000,9999)}`,fuelType:pick(["PETROL","DIESEL","CNG","ELECTRIC","HYBRID"] as const)},service:s._id,mechanic:m?._id??null,status,amount,scheduledAt:scheduled,pickupAddress:`${n(1,999)}, ${pick(areas)}, Delhi NCR`,location:loc(),notes:pick(["Regular service requested.","Customer reports unusual noise.","Please call before arrival.","Priority service requested.",""])};if(status==="IN_PROGRESS")b.startedAt=new Date(scheduled.getTime()+3600000);if(status==="COMPLETED"){b.startedAt=new Date(scheduled.getTime()+3600000);b.completedAt=new Date(scheduled.getTime()+n(2,5)*3600000);const x=stats.get(String(c._id))||{count:0,spent:0};x.count++;x.spent+=amount;stats.set(String(c._id),x);if(m)mstats.set(String(m._id),(mstats.get(String(m._id))||0)+1)}if(status==="CANCELLED")b.cancelledAt=new Date(scheduled.getTime()+n(1,24)*3600000);bookings.push(b)}
 await Booking.insertMany(bookings);
 await Promise.all([...cs.map(c=>{const x=stats.get(String(c._id))||{count:0,spent:0};return Customer.updateOne({_id:c._id},{$set:{totalBookings:x.count,totalSpent:x.spent}})}),...ms.map(m=>Mechanic.updateOne({_id:m._id},{$inc:{jobsCompleted:mstats.get(String(m._id))||0}}))]);
 console.log("Seed complete: 5 users, 120 customers, 30 mechanics, 10 services, 1250 bookings");
 console.log("Admin: admin@instantmechanic.com / Admin@123"); console.log("Operations: ops1@instantmechanic.com / Ops@123");
 await mongoose.disconnect();
}
seed().catch(async e=>{console.error("Seed failed",e);await mongoose.disconnect();process.exit(1)});
